
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build package on ROS
    runs-on: ubuntu-20.04
    container: ros:galactic

    steps:
      - name: Create ROS2 workspace
        run: |
          mkdir -p ros2_ws/src
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: 'ros2_ws/src/ros2_xsens_mti_driver'
      # - name: Install dependencies
      #   run: |
      #     rosdep update
      #     rosdep install --default-yes --from-paths ros2_ws/src/ros2_xsens_mti_driver
      - name: Build using colcon
        run: |
          . /opt/ros/galactic/setup.sh
          cd ros2_ws
          colcon build --event-handlers console_cohesion+
